### ISSUE TITLE
E2E-Test NoCustomersOnCardView() - pathes for .whenGET need fixing

### ISSUE THREAD

**Issue by RoDo777** [DanWahlin/CustomerManagerStandard#24]
````javascript
//$httpBackend.whenGET(/^\/app\/partials\//).passThrough();  // line 80
$httpBackend.whenGET(/^\/app\/customersApp\/partials\//).passThrough();
````
````javascript
//$httpBackend.whenGET(/^\/app\/views\//).passThrough();  // line 82
$httpBackend.whenGET(/^\/app\/customersApp\/views\//).passThrough();
````
And you can omit the leading \ after .whenGET(' ...
````javascript
$httpBackend.whenGET('\/api/...  // Line 84
````

**Comment by DanWahlin** [comment]
Thanks! Appreciate the information. I didn't create the original tests (someone was nice to contribute a pull request) but will try to get this integrated in when I get a chance.

If you're able to fork the project, make the updates, and then do a pull request I'll happily take that. :-) Thanks again.
