### ISSUE TITLE
How can I run it on webstorm

### ISSUE THREAD

**Issue by Romulus79** [DanWahlin/CustomerManagerStandard#27]
I tried to run npm install in the CustomerManager folder but it just returned:
npm WARN package.json CustomerManager@1.0.0 No description
npm WARN package.json CustomerManager@1.0.0 No repository field.
npm WARN package.json CustomerManager@1.0.0 No README data
npm WARN package.json CustomerManager@1.0.0 No license field.
 and didn't installed anything.

**Comment by DanWahlin** [comment]
The warnings can be ignored (they're just warnings). However, not getting anything installed definitely isn't right - you should definitely see the node_modules folder added. I just ran it without issue so I suspect you might either have some type of security issue on your machine or are potentially being blocked from using npmjs.org properly by a proxy server. It's not possible to say without being able to run it. I'd try on another machine if possible and see if you're able to duplicate the issue....it definitely does work though.

**Comment by DAT14WRomulusDanielNegut** [comment]
Thank you. I will try what you said. I will use Visual Studio instead if I will not be able to use Webstorm, which is my preffered IDE.

**Comment by DanWahlin** [comment]
The problem you're having shouldn't have anything to do with the editor (unless there's something going on). Having said that, if you're running npm install from within WebStorm's console you might try running it outside first to see if that's the issue.

**Comment by DAT14WRomulusDanielNegut** [comment]
Uninstalled node, Reinstalled node, npm update, tried "npm install" from cmd with admin privileges in the CustomerManager folder = seems to install smth but not from the dependencies.
