### ISSUE TITLE
How change the text on Visual Studio?

### ISSUE THREAD

**Issue by dropyghost** [DanWahlin/CustomerManagerStandard#30]
If I change the text to the views inside visual studio 2017 and run `node server.js` I can see the translation of the text (top part of the picture) but If I run with F5 in Visual Studio (botom) still  show the original version.

```
var NavbarController = function ($scope, $location, config, authService) {
        var vm = this,
            appTitle = 'Administrador de Vendedores';

```

What I have to do in VS so take the change in the view?

![image](https://user-images.githubusercontent.com/10077853/34929101-3f9fe664-f998-11e7-8bbe-3a01b7bd37d0.png)

**Comment by dropyghost** [comment]
Yes, that work. But after each change I do. I have to Empty the Cache again. :(

**Comment by RandyDavis** [comment]
Under the settings within Chrome dev tools, there is an option to automatically clear cache on refresh as long as the dev tools are open (I think it's under the JavaScript section, but not 100% sure as I am not at a computer at the moment). 

To manually empty cache quickly in Chrome, just click and hold down the refresh icon while the dev tools are open and a menu will drop down with cache reload options ("Empty cache and hard reload" is the one you want). Hope this helps!

**Comment by DanWahlin** [comment]
Thanks Randy - great suggestion.
