### ISSUE TITLE
Is there a video for this project?

### ISSUE THREAD

**Issue by dropyghost** [DanWahlin/CustomerManagerStandard#31]
In the blog 

https://weblogs.asp.net/dwahlin/video-tutorial-angularjs-fundamentals-in-60-ish-minutes

There is a link for Customer Manager App Demo

https://www.youtube.com/watch?v=qCzYrDgOy1A

But doesnt exist anymore.

**Comment by DanWahlin** [comment]
Dropbox changed how their public links work last year which broke many links unfortunately. That's a really old post so I don't remember the specific file, but I think this was the original code it pointed to:

https://www.dropbox.com/s/3pp9yfzc7dszpyc/AngularJSDemos.zip?dl=0

**Comment by dropyghost** [comment]
Yes those are the files but I guess are the same are the one on GitHub. But I mean the YouTube video.

**Comment by DanWahlin** [comment]
Those are an early version of this project - not the same files as what is on Github at all. Those are the files the video originally pointed to (all I have at this point).
